### ISSUE TITLE
boto3 missing

### ISSUE THREAD

**Issue by cchallu** [Nixtla/fasttsfeatures#1]
ModuleNotFoundError: No module named 'boto3'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/rp/97y9_3ns23v01hdn0rp9ndw40000gp/T/ipykernel_27783/3948164789.py in <module>
----> 1 from fasttsfeatures.core import TSFeatures

~/anaconda3/envs/baas/lib/python3.7/site-packages/fasttsfeatures/core.py in <module>
      9 from typing import Optional
     10 
---> 11 import boto3
     12 import pandas as pd
     13 

ModuleNotFoundError: No module named 'boto3'

**Comment by FedericoGarza** [comment]
Solved in dac16dd2537b9ac833158095ded753c4083c9af1.

Thanks!
